name: s81_onepiece_flutterapp_libconnect
description: A minimal counter app for Flutter fundamentals assessment.
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
